name: document_scanner_flutter
description: A android & ios document scanner & auto detector plugin for flutter.
version: 0.3.0
homepage: https://github.com/ishaquehassan/document_scanner_flutter

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  pdf: ^3.4.0
  photo_view: ^0.14.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.document.scanner.flutter.document_scanner_flutter
        pluginClass: DocumentScannerFlutterPlugin
      ios:
        pluginClass: DocumentScannerFlutterPlugin
